### PR TITLE
fix(kernel): sending messages to terminated vats

### LINKED ISSUE #613: Messages to terminated vat objects cause kernel hangs instead of proper error handling
When sending messages to objects owned by terminated vats, the kernel hangs instead of properly rejecting the message with a "no vat" error. This could cause production kernel failures in scenarios involving vat crashes, rapid vat lifecycle operations, or cross-vat object sharing.

### PR DESCRIPTION
**Pull request by sirtimid**
Closes #613 

Fix when sending messages to objects owned by terminated vats, the kernel should reject the message with a "no vat" error. Added a test to validate.

### CODE REVIEW

File: packages/ocap-kernel/src/KernelRouter.ts [hunk 1]
```diff
@@ -145,7 +145,7 @@ export class KernelRouter {
       if (this.#kernelStore.isRevoked(targetObject)) {
         return routeAsSplat(kser('revoked object'));
       }
-      const vatId = this.#kernelStore.getOwner(targetObject);
+      const vatId = this.#kernelStore.getOwner(targetObject, false);
```
Comment (sirtimid) [inline packages/ocap-kernel/src/KernelRouter.ts:148]: this just prevents `getOwner` to throw

Comment (rekmarks) [reply packages/ocap-kernel/src/KernelRouter.ts:148]: Should we just get rid of the second param of `getOwner()`? Before this change it was only ever `true`, now it is only ever `false` in production code.

Comment (sirtimid) [reply packages/ocap-kernel/src/KernelRouter.ts]: Done https://github.com/MetaMask/ocap-kernel/pull/617/commits/a0a962144e815a65b2af4e5a306808aff340e70e
